### ISSUE TITLE
Survey final check boxes must be checked to submit survey

### ISSUE THREAD

**Issue by PiManASM** [williamstrong/Zophar#30]
Not much of a question then eh?

**Comment by DannyWilson1** [comment]
All the checkboxes that are used for the yes/no questions about the beliefs of the bible must be checked, which doesn't make sense because "will everybody eventually go to heaven?" and others need to be left unchecked to be correct.

**Comment by williamstrong** [comment]
We will add true or false options to the boxes with this issue.

**Comment by PiManASM** [comment]
Fixed #62
