### ISSUE TITLE
Ways to Serve page

### ISSUE THREAD

**Issue by DannyWilson1** [williamstrong/Zophar#44]
Displays users MBTI personality type
Displays recommended serving opportunities based on the fruit
Uses function "get_service_opportunities" from the ML group to determine what is displayed

This was the original diagram trying to depict the information displayed (as well as how the function should work):
[(https://docs.google.com/drawings/d/1rUwHcztT0x53eprFAP1Ica005cTV_n6QodWrNVHJEjM/edit?usp=sharing)]

**Comment by PiManASM** [comment]
Thanks Ryan for the hotfix #76
