### ISSUE TITLE
Tracker Page

### ISSUE THREAD

**Issue by DannyWilson1** [williamstrong/Zophar#49]
Instead of recording the time of reading you have completed by a drop down box that only measures in hours:

A page with a "start" and "stop" button that records the time would be nice. 
Possibly accessible through: 1. a button on the accountability, or 2. a button on the main menu, or 3. just be at the top of the accountability page. Up to you.

Image of what this looks like is below:
![trackerpage](https://user-images.githubusercontent.com/35618128/38636437-03dfa71c-3d7d-11e8-93d7-27ca83b7ef75.jpg)

**Comment by PiManASM** [comment]
fixed: https://play.google.com/store/apps/details?id=com.sportstracklive.stopwatch&hl=en
